Fix path issues when loading unzipped csv
This commit fixes an error when a missing '/' at the end of the path will loading the raw csv data into spark. Note that, if the path is already suffixed by a '/', this will add an additional '/' but this will not loading the file.

    paramsString: String = -Dunicef_traffic_W_2015_01.csv,admin0,/tmp/unzipped-1eXloo7PJntEn,/tmp/spark_output-1S5tRglKrH47J
    paramsArray: Array[String] = Array(unicef_traffic_W_2015_01.csv, admin0, /tmp/unzipped-1eXloo7PJntEn, /tmp/spark_output-1S5tRglKrH47J)
    filename: String = unicef_traffic_W_2015_01.csv
    aggregation_level: String = admin0
    path_unzipped: String = /tmp/unzipped-1eXloo7PJntEn
    path_temp: String = /tmp/spark_output-1S5tRglKrH47J
    org.apache.spark.sql.AnalysisException: Path does not exist: file:/tmp/unzipped-1eXloo7PJntEnunicef_traffic_W_2015_01.csv;